elemento:
    path:     /
    defaults: { _controller: "AmbientesCidmBundle:Elemento:index" }

elemento_show:
    path:     /{id}/show
    defaults: { _controller: "AmbientesCidmBundle:Elemento:show" }

elemento_new:
    path:     /new
    defaults: { _controller: "AmbientesCidmBundle:Elemento:new" }

elemento_create:
    path:     /create
    defaults: { _controller: "AmbientesCidmBundle:Elemento:create" }
    requirements: { _method: post }

elemento_edit:
    path:     /{id}/edit
    defaults: { _controller: "AmbientesCidmBundle:Elemento:edit" }

elemento_update:
    path:     /{id}/update
    defaults: { _controller: "AmbientesCidmBundle:Elemento:update" }
    requirements: { _method: post|put }

elemento_delete:
    path:     /{id}/delete
    defaults: { _controller: "AmbientesCidmBundle:Elemento:delete" }
    requirements: { _method: post|delete }
