estadousuario:
    path:     /
    defaults: { _controller: "AmbientesCidmBundle:EstadoUsuario:index" }

estadousuario_show:
    path:     /{id}/show
    defaults: { _controller: "AmbientesCidmBundle:EstadoUsuario:show" }

estadousuario_new:
    path:     /new
    defaults: { _controller: "AmbientesCidmBundle:EstadoUsuario:new" }

estadousuario_create:
    path:     /create
    defaults: { _controller: "AmbientesCidmBundle:EstadoUsuario:create" }
    requirements: { _method: post }

estadousuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "AmbientesCidmBundle:EstadoUsuario:edit" }

estadousuario_update:
    path:     /{id}/update
    defaults: { _controller: "AmbientesCidmBundle:EstadoUsuario:update" }
    requirements: { _method: post|put }

estadousuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "AmbientesCidmBundle:EstadoUsuario:delete" }
    requirements: { _method: post|delete }
