Ambientes\CidmBundle\Entity\AccesoAmbientes:
    type: entity
    table: acceso_ambientes
    indexes:
        FK_RELATIONSHIP_19:
            columns:
                - ID_ESTADO
        FK_RELATIONSHIP_20:
            columns:
                - ID_EVENTO
    id:
        idAcceso:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID_ACCESO
            generator:
                strategy: IDENTITY
    fields:
        fechaCompleta:
            type: date
            nullable: true
            comment: ''
            column: FECHA_COMPLETA
        observaciones:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
            column: OBSERVACIONES
    manyToOne:
        idEstado:
            targetEntity: EstadoAccesoAmbientes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_ESTADO:
                    referencedColumnName: ID_ESTADO
            orphanRemoval: false
        idEvento:
            targetEntity: Evento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_EVENTO:
                    referencedColumnName: ID_EVENTO
            orphanRemoval: false
    lifecycleCallbacks: {  }
