Ambientes\CidmBundle\Entity\Ambiente:
    type: entity
    table: ambiente
    indexes:
        FK_RELATIONSHIP_2:
            columns:
                - ID_CENTRO
    id:
        idAmbiente:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID_AMBIENTE
            generator:
                strategy: IDENTITY
    fields:
        codigo:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: CODIGO
        nombre:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: NOMBRE
        descripcion:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
            column: DESCRIPCION
        puestosTrabajo:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: PUESTOS_TRABAJO
    manyToOne:
        idCentro:
            targetEntity: CentroFormacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_CENTRO:
                    referencedColumnName: ID_CENTRO
            orphanRemoval: false
    lifecycleCallbacks: {  }
