Ambientes\CidmBundle\Entity\EstadoAccesoAmbientes:
    type: entity
    table: estado_acceso_ambientes
    id:
        idEstado:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID_ESTADO
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
            column: DESCRIPCION
    lifecycleCallbacks: {  }
