Ambientes\CidmBundle\Entity\Solicitud:
    type: entity
    table: solicitud
    indexes:
        FK_RELATIONSHIP_3:
            columns:
                - ID_AMBIENTE
    id:
        idSolicitud:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID_SOLICITUD
            generator:
                strategy: IDENTITY
    fields:
        idUsuario:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: ID_USUARIO
        fechaSolicitud:
            type: date
            nullable: true
            comment: ''
            column: FECHA_SOLICITUD
        fechaRespuesta:
            type: date
            nullable: true
            comment: ''
            column: FECHA_RESPUESTA
        fechaInicio:
            type: date
            nullable: true
            comment: ''
            column: FECHA_INICIO
        fechaFin:
            type: date
            nullable: true
            comment: ''
            column: FECHA_FIN
        horaInicio:
            type: time
            nullable: true
            comment: ''
            column: HORA_INICIO
        horaFin:
            type: time
            nullable: true
            comment: ''
            column: HORA_FIN
        estado:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
            column: ESTADO
        numeroPersonas:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: NUMERO_PERSONAS
    manyToOne:
        idAmbiente:
            targetEntity: Ambiente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_AMBIENTE:
                    referencedColumnName: ID_AMBIENTE
            orphanRemoval: false
    lifecycleCallbacks: {  }
